import solc from "solc";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
const source = readFileSync("contracts/BitMarket.sol", "utf8");
const input = {
  language: "Solidity",
  sources: { "BitMarket.sol": { content: source } },
  settings: {
    evmVersion: "paris",
    optimizer: { enabled: true, runs: 200 },
    outputSelection: {
      "*": {
        "*": [
          "abi",
          "evm.bytecode.object",
          "evm.deployedBytecode.object",
          "metadata",
        ],
      },
    },
  },
};
const output = JSON.parse(solc.compile(JSON.stringify(input)));
for (const error of output.errors || []) {
  if (error.severity === "error") throw new Error(error.formattedMessage);
}
export const artifact = output.contracts["BitMarket.sol"].BitMarket;
mkdirSync("artifacts", { recursive: true });
writeFileSync("artifacts/BitMarket.json", JSON.stringify(artifact, null, 2));
writeFileSync(
  "lib/abi.ts",
  `// Generated by npm run contracts:compile.\nexport const marketplaceAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);
writeFileSync("artifacts/compiler-input.json", JSON.stringify(input));
console.log("Compiled BitMarket with Solidity " + solc.version());
